# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmaster.proto\x12\x06master\"\xcc\x01\n\x12MapperInputRequest\x12\x39\n\x0b\x64\x61ta_points\x18\x01 \x03(\x0b\x32$.master.MapperInputRequest.DataPoint\x12\x36\n\tcentroids\x18\x02 \x03(\x0b\x32#.master.MapperInputRequest.Centroid\x1a!\n\tDataPoint\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x1a \n\x08\x43\x65ntroid\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"%\n\x13MapperInputResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32P\n\x06Master\x12\x46\n\x0bMapperInput\x12\x1a.master.MapperInputRequest\x1a\x1b.master.MapperInputResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPPERINPUTREQUEST']._serialized_start=25
  _globals['_MAPPERINPUTREQUEST']._serialized_end=229
  _globals['_MAPPERINPUTREQUEST_DATAPOINT']._serialized_start=162
  _globals['_MAPPERINPUTREQUEST_DATAPOINT']._serialized_end=195
  _globals['_MAPPERINPUTREQUEST_CENTROID']._serialized_start=197
  _globals['_MAPPERINPUTREQUEST_CENTROID']._serialized_end=229
  _globals['_MAPPERINPUTRESPONSE']._serialized_start=231
  _globals['_MAPPERINPUTRESPONSE']._serialized_end=268
  _globals['_MASTER']._serialized_start=270
  _globals['_MASTER']._serialized_end=350
# @@protoc_insertion_point(module_scope)
